"""
Load CSV data into Snowflake using snowflake-connector-python.

Alternative to the SnowSQL CLI approach in sql/load_snowflake.sql.
Uses write_pandas for bulk loading, which internally uses PUT + COPY INTO.

Usage:
    cp .env.example .env   # fill in your credentials
    pip install snowflake-connector-python[pandas] python-dotenv pandas
    python load_to_snowflake.py
"""

import logging
import os
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv
from snowflake.connector import connect
from snowflake.connector.pandas_tools import write_pandas

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)

load_dotenv()

# Required env vars
SNOWFLAKE_ACCOUNT = os.environ["SNOWFLAKE_ACCOUNT"]
SNOWFLAKE_USER = os.environ["SNOWFLAKE_USER"]
SNOWFLAKE_PASSWORD = os.environ["SNOWFLAKE_PASSWORD"]
SNOWFLAKE_DATABASE = os.getenv("SNOWFLAKE_DATABASE", "PHARMA_ANALYTICS")
SNOWFLAKE_SCHEMA = os.getenv("SNOWFLAKE_SCHEMA", "RAW")
SNOWFLAKE_WAREHOUSE = os.getenv("SNOWFLAKE_WAREHOUSE", "PHARMA_WH")

DATA_DIR = Path(__file__).parent / "data"

# Load order: dimensions first, then facts
TABLES = [
    ("dim_patients", "dim_patients.csv"),
    ("dim_payers", "dim_payers.csv"),
    ("dim_pharmacies", "dim_pharmacies.csv"),
    ("dim_drugs", "dim_drugs.csv"),
    ("dim_dates", "dim_dates.csv"),
    ("fact_rx_fills", "fact_rx_fills.csv"),
    ("fact_shipments", "fact_shipments.csv"),
]

# Columns to skip on load (auto-generated by Snowflake)
SKIP_COLUMNS = {
    "fact_shipments": ["shipment_id"],
}


def load_table(conn, table_name: str, csv_file: str) -> int:
    """Load a single CSV into a Snowflake table. Returns row count."""
    filepath = DATA_DIR / csv_file
    if not filepath.exists():
        raise FileNotFoundError(f"Missing: {filepath}")

    df = pd.read_csv(filepath)

    # Drop auto-generated columns
    skip = SKIP_COLUMNS.get(table_name, [])
    for col in skip:
        if col in df.columns:
            df = df.drop(columns=[col])

    # Snowflake expects uppercase column names
    df.columns = [c.upper() for c in df.columns]

    logger.info(f"Loading {table_name}: {len(df)} rows, columns={list(df.columns)}")

    success, num_chunks, num_rows, _ = write_pandas(
        conn,
        df,
        table_name.upper(),
        auto_create_table=False,
        overwrite=True,
    )

    if not success:
        raise RuntimeError(f"Failed to load {table_name}")

    logger.info(f"  {table_name}: {num_rows} rows loaded in {num_chunks} chunk(s)")
    return num_rows


def validate_counts(conn) -> None:
    """Run row count validation after loading."""
    expected = {
        "DIM_PATIENTS": 500,
        "DIM_PAYERS": 5,
        "DIM_PHARMACIES": 10,
        "DIM_DRUGS": 5,
        "DIM_DATES": 731,
        "FACT_RX_FILLS": 3000,
        "FACT_SHIPMENTS": 240,
    }

    cursor = conn.cursor()
    all_ok = True
    for table, expected_count in expected.items():
        cursor.execute(f"SELECT COUNT(*) FROM {table}")
        actual = cursor.fetchone()[0]
        status = "OK" if actual == expected_count else "MISMATCH"
        if status == "MISMATCH":
            all_ok = False
        logger.info(f"  {table}: {actual} rows (expected {expected_count}) [{status}]")

    if all_ok:
        logger.info("All row counts validated.")
    else:
        logger.warning("Row count mismatches detected. Review output above.")


def main() -> None:
    logger.info(f"Connecting to {SNOWFLAKE_ACCOUNT}, db={SNOWFLAKE_DATABASE}, schema={SNOWFLAKE_SCHEMA}")

    conn = connect(
        account=SNOWFLAKE_ACCOUNT,
        user=SNOWFLAKE_USER,
        password=SNOWFLAKE_PASSWORD,
        database=SNOWFLAKE_DATABASE,
        schema=SNOWFLAKE_SCHEMA,
        warehouse=SNOWFLAKE_WAREHOUSE,
    )

    try:
        # Create schema if needed
        conn.cursor().execute(f"CREATE SCHEMA IF NOT EXISTS {SNOWFLAKE_SCHEMA}")
        conn.cursor().execute(f"USE SCHEMA {SNOWFLAKE_SCHEMA}")

        # Create tables from schema.sql
        schema_path = Path(__file__).parent / "sql" / "schema.sql"
        if schema_path.exists():
            logger.info("Running schema.sql to create tables...")
            schema_sql = schema_path.read_text()
            for stmt in schema_sql.split(";"):
                stmt = stmt.strip()
                if stmt and not stmt.startswith("--"):
                    conn.cursor().execute(stmt)

        # Load data
        total_rows = 0
        for table_name, csv_file in TABLES:
            rows = load_table(conn, table_name, csv_file)
            total_rows += rows

        logger.info(f"Total rows loaded: {total_rows}")

        # Validate
        logger.info("Validating row counts...")
        validate_counts(conn)

    finally:
        conn.close()
        logger.info("Connection closed.")


if __name__ == "__main__":
    main()
